accounts/urls.py
from django.urls import path 

from accounts.views import ForumLoginView, ForumSignUpView

urlpatterns = [ 
    path('login/', ForumLoginView.as_view(), name='login'),
    path('signup/', ForumSignUpView.as_view(), name='signup')
]

forums/urls.py
from django.urls import path 

from forums.views import (
    CommentCreateView, DiscussionDetailView, 
    ForumCreateView, 
    ForumListView,
    ForumDetailView,
    DiscussionCreateView
)

urlpatterns = [ 
    path('f/all/', ForumListView.as_view(), name='forum-home'),
    path('f/new/', ForumCreateView.as_view(), name='forum-new'),
    path('f/<slug:slug>/', ForumDetailView.as_view(), name='forum-detail'),

    path('d/<slug:slug>/new/', DiscussionCreateView.as_view(), name='discussion-new'),
    path('d/<slug:slug>/', DiscussionDetailView.as_view(), name='discussion-detail'),

    path('d/<slug:slug>/comment/add/', CommentCreateView.as_view(), name='comment-add')
]

openforum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('forums.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

forums/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User

class Forum(models.Model):
    name = models.CharField(max_length=128)
    slug = models.SlugField(null=False, unique=True)
    author = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('forum-detail', kwargs={'slug':self.slug})

class Discussion(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=128)
    body = models.TextField()
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    forum = models.ForeignKey(
        Forum,
        on_delete=models.CASCADE
    )
    slug = models.SlugField(null=False, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('discussion-detail', kwargs={'slug':self.slug})

class Comment(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    author = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING
    )
    discussion = models.ForeignKey(
        Discussion,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.body[:50]

    def get_absolute_url(self):
        return reverse('discussion-detail', kwargs={'slug': self.discussion.slug})

accounts/views.py
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from django.contrib.auth.models import User

class ForumLoginView(LoginView):
    template_name = 'registration/login.html'

class ForumSignUpView(CreateView):
    model = User
    fields = (
        'first_name', 'last_name', 
        'username', 'password'
    )
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('login')
    

forums/views.py
from django.views.generic import (
    ListView,
    DetailView,
    CreateView
)

from forums.models import (
    Forum,
    Discussion,
    Comment
)

from forums.sanitizers import slug_clean

class ForumListView(ListView):
    model = Forum 
    template_name = 'forums/home.html'
    context_object_name = 'forums'

class ForumDetailView(DetailView):
    model = Forum 
    template_name = 'forums/detail.html'
    context_object_name = 'forum'

class DiscussionDetailView(DetailView):
    model = Discussion 
    template_name = 'discussion/detail.html'
    context_object_name = 'discussion'

class ForumCreateView(CreateView):
    model = Forum 
    template_name = 'forums/new.html'
    fields = ('name', )

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.name = form.instance.name.title()
        form.instance.slug = slug_clean(
            self.model,
            form.instance.name.lower()
        )
        return super().form_valid(form)

class DiscussionCreateView(CreateView):
    model = Discussion 
    template_name = 'discussion/new.html'
    fields = ('title', 'body', )

    def form_valid(self, form):
        form.instance.author = self.request.user 
        form.instance.slug = slug_clean(
            self.model,
            form.instance.title.lower()
        )
        form.instance.forum = Forum.objects.get(slug=self.kwargs['slug'])
        return super().form_valid(form)

class CommentCreateView(CreateView):
    model = Comment
    template_name = 'comment/add.html'
    fields = ('body', )

    def form_valid(self, form):
        form.instance.author = self.request.user 
        form.instance.discussion = Discussion.objects.get(slug=self.kwargs['slug'])
        return super().form_valid(form)

templates/comment/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}Add Comment{% endblock title %}

{% block content %} 
    <h1 class="title">Add Comment</h1>
    <div class="columns">
        <div class="column is-half">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="button is-success">Add</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/discussion/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}{{ discussion.title }}{% endblock title %}

{% block content %} 
    <div class="content">
        <div class="columns">
            <div class="column is-three-fifths">
                <div class="section">
                    <h1 class="title mb-6">
                      {{ discussion.title|title }}
                      <span class="tag is-primary">{{ discussion.forum.name }}</span>
                    </h1>
                    
                    <h4 class="subtitle is-6">
                        by {{ discussion.author}} | {{ discussion.date }}
                    </h2>
                    <p>
                        {{ discussion.body }}
                    </p>
                </div>
                <div class="section has-background-white-ter">
                    <div class="columns">
                        <div class="column">
                            <h4 class="subtitle">All Comments</h4>
                        </div>
                        <div class="column">
                            <a class="button is-success is-light" 
                            href="{% url 'comment-add' discussion.slug %}">+ Add Comment</a>
                        </div>
                    </div>
                    {% for comment in discussion.comment_set.all %}
                        <div class="card mb-4">
                            <div class="card-content">
                                <p class="title is-6 mb-6">{{ comment.body }}</p>
                                <p class="subtitle is-6">
                                    by {{ comment.author }} | {{ comment.date }}
                                </p>
                                {% if user.is_authenticated and comment.author == user %}
                                <footer class="card-footer">
                                    <a href="#" class="card-footer-item">Edit</a>
                                    <a href="#" class="card-footer-item">Delete</a>
                                </footer>
                                {% endif %}
                            </div>
                        </div>
                    {% empty %}
                        <p>No comments available.</p>
                    {% endfor %}
                </div>
            </div>
            <div class="column">
                adassdds
            </div>
        </div>

    </div>
    
{% endblock content %}

templates/discussion/new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}New Discussion{% endblock title %}

{% block content %} 
    <h1 class="title">New Discussion</h1>
    <div class="columns">
        <div class="column is-half">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="button is-success">Add</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/forums/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}{{ forum.name }}{% endblock title %}

{% block content %} 
    <div class="content">
          <div class="section">
            <div class="columns">
              <div class="column">
                <h1 class="title">{{ forum.name }}</h1>
              </div>
              <div class="column">
                <a class="button is-success is-light" 
                href="{% url 'discussion-new' forum.slug %}">+ Add Discussion</a>
              </div>
            </div>
          </div>
          {% for discussion in forum.discussion_set.all %}
           <div class="card mb-6">
              <div class="card-content">
                <p class="title">
                  {% filter force_escape|title %}
                  {{ discussion.title }}
                  {% endfilter %}
                </p>
                <p class="subtitle">
                  by {{ discussion.author }} | 
                  {{ discussion.date }}
                </p>
              </div>
              <footer class="card-footer">
                <p class="card-footer-item">
                  <span>
                    View on <a href="{{ discussion.get_absolute_url }}">more</a>
                  </span>
                </p>
                <p class="card-footer-item">
                  <span>
                    Share on <a href="#">Facebook</a>
                  </span>
                </p>
              </footer>
            </div>
          {% endfor %}
        </div>
    </div>
    
{% endblock content %}

templates/forums/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %} Home {% endblock title %}

{% block content %} 
    <div class="section">
      <div class="columns">
        <div class="column">
          <h1 class="title">All Forums</h1>
        </div>
        <div class="column">
          <button class="button is-success is-light">
            <a href="{% url 'forum-new'%}">+ Add Forum</a>
          </button>
        </div>
      </div>
    </div>
    <div class="section">
      {% for forum in forums %}
      <div class="card">
          <div class="card-content">
            <p class="title">
              {{ forum.name|title }}
            </p>
          </div>
          <footer class="card-footer">
            <p class="card-footer-item">
              <span>
                  View all <a href="{{ forum.get_absolute_url }}">discussions</a>
              </span>
            </p>
            <p class="card-footer-item">
              <span>
                Share on <a href="#">Facebook</a>
              </span>
            </p>
          </footer>
        </div>
      {% endfor %}
    </div>
{% endblock content %}

templates/forums/new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}New Forum{% endblock title %}

{% block content %} 
    <h1 class="title">New Forum</h1>
    <div class="columns">
        <div class="column is-half">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="button is-success">Add</button>
            </form>
        </div>
    </div>
{% endblock content %}